<a href="https://colab.research.google.com/github/VATHSAV2004/EDA_imp_libraries/blob/main/Pandas_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.Dataframes

In [98]:
import pandas as pd

In [99]:
employee1=pd.Series({'Name':'Utkarsh','ID':1,'Gender':'Male','Salary':95000})
employee2=pd.Series({'Name':'Kartik','ID':2,'Gender':'Male','Salary':85000})
employee3=pd.Series({'Name':'Aishwarya','ID':3,'Gender':'Female','Salary':75000})
employee4=pd.Series({'Name':'Anand','ID':4,'Gender':'Male','Salary':65000})
employee5=pd.Series({'Name':'Shalini','ID':5,'Gender':'Male','Salary':90000})
employee6=pd.Series({'Name':'Pratik','ID':6,'Gender':'Male','Salary':80000})
employee7=pd.Series({'Name':'Monalika','ID':7,'Gender':'Female','Salary':70000})
employee8=pd.Series({'Name':'Ayesha','ID':8,'Gender':'Female','Salary':60000})
employee9=pd.Series({'Name':'Anant','ID':9,'Gender':'Male','Salary':100000})
employee10=pd.Series({'Name':'Shamiksha','ID':10,'Gender':'Female','Salary':45000})
employee11=pd.Series({'Name':'Prashant','ID':11,'Gender':'Male','Salary':55000})
employee12=pd.Series({'Name':'Mohini','ID':12,'Gender':'Female','Salary':65000})

In [100]:
employee1

Name      Utkarsh
ID              1
Gender       Male
Salary      95000
dtype: object

In [101]:
employees=[employee1,employee2,employee3,employee4,employee5,employee6,employee7,employee8,employee9,employee10,employee11,employee12]
df1=pd.DataFrame(data=employees,index=range(101,113))
df1

          Name  ID  Gender  Salary
101    Utkarsh   1    Male   95000
102     Kartik   2    Male   85000
103  Aishwarya   3  Female   75000
104      Anand   4    Male   65000
105    Shalini   5    Male   90000
106     Pratik   6    Male   80000
107   Monalika   7  Female   70000
108     Ayesha   8  Female   60000
109      Anant   9    Male  100000
110  Shamiksha  10  Female   45000
111   Prashant  11    Male   55000
112     Mohini  12  Female   65000

- For single and two dimensional data
- Rows and column format
- Tabular data
- Structured data
- unstructured data

In [102]:
df1.head()

          Name  ID  Gender  Salary
101    Utkarsh   1    Male   95000
102     Kartik   2    Male   85000
103  Aishwarya   3  Female   75000
104      Anand   4    Male   65000
105    Shalini   5    Male   90000

In [103]:
type(df1)

pandas.core.frame.DataFrame

In [104]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 101 to 112
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    12 non-null     object
 1   ID      12 non-null     int64
 2   Gender  12 non-null     object
 3   Salary  12 non-null     int64
dtypes: int64(2), object(2)
memory usage: 516.0+ bytes

In [105]:
df1.index

RangeIndex(start=101, stop=113, step=1)

In [106]:
df1.values

array([['Utkarsh', 1, 'Male', 95000],
       ['Kartik', 2, 'Male', 85000],
       ['Aishwarya', 3, 'Female', 75000],
       ['Anand', 4, 'Male', 65000],
       ['Shalini', 5, 'Male', 90000],
       ['Pratik', 6, 'Male', 80000],
       ['Monalika', 7, 'Female', 70000],
       ['Ayesha', 8, 'Female', 60000],
       ['Anant', 9, 'Male', 100000],
       ['Shamiksha', 10, 'Female', 45000],
       ['Prashant', 11, 'Male', 55000],
       ['Mohini', 12, 'Female', 65000]], dtype=object)

In [107]:
df1.columns

Index(['Name', 'ID', 'Gender', 'Salary'], dtype='object')

In [108]:
df1.name='Employee_Details'
df1.index.name='Employee_ID'

In [109]:
df1.name

'Employee_Details'

In [110]:
df1.index.name

'Employee_ID'

In [111]:
df1

                  Name  ID  Gender  Salary
Employee_ID
101            Utkarsh   1    Male   95000
102             Kartik   2    Male   85000
103          Aishwarya   3  Female   75000
104              Anand   4    Male   65000
105            Shalini   5    Male   90000
106             Pratik   6    Male   80000
107           Monalika   7  Female   70000
108             Ayesha   8  Female   60000
109              Anant   9    Male  100000
110          Shamiksha  10  Female   45000
111           Prashant  11    Male   55000
112             Mohini  12  Female   65000

In [112]:
df1.describe() # describe the numeric columns

              ID         Salary
count  12.000000      12.000000
mean    6.500000   73750.000000
std     3.605551   16804.355496
min     1.000000   45000.000000
25%     3.750000   63750.000000
50%     6.500000   72500.000000
75%     9.250000   86250.000000
max    12.000000  100000.000000

## Accessing data from DataFrame

In [113]:
df1['Name']

Employee_ID
101      Utkarsh
102       Kartik
103    Aishwarya
104        Anand
105      Shalini
106       Pratik
107     Monalika
108       Ayesha
109        Anant
110    Shamiksha
111     Prashant
112       Mohini
Name: Name, dtype: object

In [114]:
type(df1['Name'])

pandas.core.series.Series

In [115]:
df1[['Name','Salary']]

                  Name  Salary
Employee_ID
101            Utkarsh   95000
102             Kartik   85000
103          Aishwarya   75000
104              Anand   65000
105            Shalini   90000
106             Pratik   80000
107           Monalika   70000
108             Ayesha   60000
109              Anant  100000
110          Shamiksha   45000
111           Prashant   55000
112             Mohini   65000

In [116]:
type(df1[['Name','Salary']])

pandas.core.frame.DataFrame

In [117]:
df1.Name # coumns of datafram are also its attributes

Employee_ID
101      Utkarsh
102       Kartik
103    Aishwarya
104        Anand
105      Shalini
106       Pratik
107     Monalika
108       Ayesha
109        Anant
110    Shamiksha
111     Prashant
112       Mohini
Name: Name, dtype: object

In [118]:
df1.Salary

Employee_ID
101     95000
102     85000
103     75000
104     65000
105     90000
106     80000
107     70000
108     60000
109    100000
110     45000
111     55000
112     65000
Name: Salary, dtype: int64

In [119]:
df1.loc[101] #providing index

Name      Utkarsh
ID              1
Gender       Male
Salary      95000
Name: 101, dtype: object

In [120]:
df1.iloc[0] #default indexing

Name      Utkarsh
ID              1
Gender       Male
Salary      95000
Name: 101, dtype: object

In [121]:
df1.loc[105]

Name      Shalini
ID              5
Gender       Male
Salary      90000
Name: 105, dtype: object

In [122]:
type(df1.loc[105])

pandas.core.series.Series

In [123]:
df1.loc[[101,105,109]]

                Name  ID Gender  Salary
Employee_ID
101          Utkarsh   1   Male   95000
105          Shalini   5   Male   90000
109            Anant   9   Male  100000

In [124]:
type(df1.loc[[101,105,109]])

pandas.core.frame.DataFrame

In [125]:
df1

                  Name  ID  Gender  Salary
Employee_ID
101            Utkarsh   1    Male   95000
102             Kartik   2    Male   85000
103          Aishwarya   3  Female   75000
104              Anand   4    Male   65000
105            Shalini   5    Male   90000
106             Pratik   6    Male   80000
107           Monalika   7  Female   70000
108             Ayesha   8  Female   60000
109              Anant   9    Male  100000
110          Shamiksha  10  Female   45000
111           Prashant  11    Male   55000
112             Mohini  12  Female   65000

In [126]:
df1.loc[105]['Salary']

np.int64(90000)

In [127]:
df1.iloc[3]['Name']

'Anand'

In [128]:
df1['Salary'][103]

np.int64(75000)

In [129]:
df1['Name'][105]

'Shalini'

In [130]:
df1.Salary[105]

np.int64(90000)

In [131]:
df1.loc[[101,105,108]]['Salary']

Employee_ID
101    95000
105    90000
108    60000
Name: Salary, dtype: int64

In [132]:
df1.loc[[101,105,108]][['Name','Salary']]

                Name  Salary
Employee_ID
101          Utkarsh   95000
105          Shalini   90000
108           Ayesha   60000

In [133]:
df1.loc[105,'Salary'] #simple for above

np.int64(90000)

In [134]:
df1.loc[[105,108,110],['Name','Salary']]

                  Name  Salary
Employee_ID
105            Shalini   90000
108             Ayesha   60000
110          Shamiksha   45000

In [135]:
df1.loc[101:106] #both are inclusive ***

                  Name  ID  Gender  Salary
Employee_ID
101            Utkarsh   1    Male   95000
102             Kartik   2    Male   85000
103          Aishwarya   3  Female   75000
104              Anand   4    Male   65000
105            Shalini   5    Male   90000
106             Pratik   6    Male   80000

In [136]:
temp=df1.loc[105]
temp

Name      Shalini
ID              5
Gender       Male
Salary      90000
Name: 105, dtype: object

In [137]:
temp['Salary']

np.int64(90000)

In [138]:
df1.loc[105]['Salary']

np.int64(90000)

In [139]:
df1.Salary[105]

np.int64(90000)

In [140]:
df1.Salary.loc[105]

np.int64(90000)

In [141]:
# df1[105] gives error
# But if 105 is not a column name, you’ll get a KeyError because:

# For DataFrames, df[<something>] looks for columns, not rows.
# For series it works
#For Series: [] → index-based lookup (like a dict).

#For DataFrame: [] → column selection (like a dict of Series).

In [142]:
df1.Name[105]

'Shalini'

In [143]:
df1.iloc[[0,4,7,9]][['Name','Salary']]

                  Name  Salary
Employee_ID
101            Utkarsh   95000
105            Shalini   90000
108             Ayesha   60000
110          Shamiksha   45000

In [144]:
df1.loc[[105,108,110,101],['Name','Salary']]

                  Name  Salary
Employee_ID
105            Shalini   90000
108             Ayesha   60000
110          Shamiksha   45000
101            Utkarsh   95000

## Adding and Deleting Rows and Columns

In [145]:
df1

                  Name  ID  Gender  Salary
Employee_ID
101            Utkarsh   1    Male   95000
102             Kartik   2    Male   85000
103          Aishwarya   3  Female   75000
104              Anand   4    Male   65000
105            Shalini   5    Male   90000
106             Pratik   6    Male   80000
107           Monalika   7  Female   70000
108             Ayesha   8  Female   60000
109              Anant   9    Male  100000
110          Shamiksha  10  Female   45000
111           Prashant  11    Male   55000
112             Mohini  12  Female   65000

In [146]:
df1.loc[113]=['Priti',13,'Femal',71000]

In [147]:
df1

                  Name  ID  Gender  Salary
Employee_ID
101            Utkarsh   1    Male   95000
102             Kartik   2    Male   85000
103          Aishwarya   3  Female   75000
104              Anand   4    Male   65000
105            Shalini   5    Male   90000
106             Pratik   6    Male   80000
107           Monalika   7  Female   70000
108             Ayesha   8  Female   60000
109              Anant   9    Male  100000
110          Shamiksha  10  Female   45000
111           Prashant  11    Male   55000
112             Mohini  12  Female   65000
113              Priti  13   Femal   71000

In [148]:
import numpy as np
import random
df1['Age']=np.random.randint(25,50,13)

In [149]:
df1

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male   95000   37
102             Kartik   2    Male   85000   41
103          Aishwarya   3  Female   75000   41
104              Anand   4    Male   65000   46
105            Shalini   5    Male   90000   44
106             Pratik   6    Male   80000   30
107           Monalika   7  Female   70000   32
108             Ayesha   8  Female   60000   42
109              Anant   9    Male  100000   39
110          Shamiksha  10  Female   45000   38
111           Prashant  11    Male   55000   39
112             Mohini  12  Female   65000   25
113              Priti  13   Femal   71000   42

In [150]:
df1.drop(113,inplace=True,axis=0) #Without axis, Pandas can’t switch between rows/columns. But they set axis=0 as default since most people drop rows more often.

In [151]:
df1

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male   95000   37
102             Kartik   2    Male   85000   41
103          Aishwarya   3  Female   75000   41
104              Anand   4    Male   65000   46
105            Shalini   5    Male   90000   44
106             Pratik   6    Male   80000   30
107           Monalika   7  Female   70000   32
108             Ayesha   8  Female   60000   42
109              Anant   9    Male  100000   39
110          Shamiksha  10  Female   45000   38
111           Prashant  11    Male   55000   39
112             Mohini  12  Female   65000   25

In [152]:
df1['City']='Jaipur' # if we provide one then all are same other wise list of different
df1

                  Name  ID  Gender  Salary  Age    City
Employee_ID
101            Utkarsh   1    Male   95000   37  Jaipur
102             Kartik   2    Male   85000   41  Jaipur
103          Aishwarya   3  Female   75000   41  Jaipur
104              Anand   4    Male   65000   46  Jaipur
105            Shalini   5    Male   90000   44  Jaipur
106             Pratik   6    Male   80000   30  Jaipur
107           Monalika   7  Female   70000   32  Jaipur
108             Ayesha   8  Female   60000   42  Jaipur
109              Anant   9    Male  100000   39  Jaipur
110          Shamiksha  10  Female   45000   38  Jaipur
111           Prashant  11    Male   55000   39  Jaipur
112             Mohini  12  Female   65000   25  Jaipur

In [153]:
df1.drop('City',axis=1) #without axis=1 it search by default for row

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male   95000   37
102             Kartik   2    Male   85000   41
103          Aishwarya   3  Female   75000   41
104              Anand   4    Male   65000   46
105            Shalini   5    Male   90000   44
106             Pratik   6    Male   80000   30
107           Monalika   7  Female   70000   32
108             Ayesha   8  Female   60000   42
109              Anant   9    Male  100000   39
110          Shamiksha  10  Female   45000   38
111           Prashant  11    Male   55000   39
112             Mohini  12  Female   65000   25

In [154]:
df1.drop('City',axis=1,inplace=True)

In [155]:
df1

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male   95000   37
102             Kartik   2    Male   85000   41
103          Aishwarya   3  Female   75000   41
104              Anand   4    Male   65000   46
105            Shalini   5    Male   90000   44
106             Pratik   6    Male   80000   30
107           Monalika   7  Female   70000   32
108             Ayesha   8  Female   60000   42
109              Anant   9    Male  100000   39
110          Shamiksha  10  Female   45000   38
111           Prashant  11    Male   55000   39
112             Mohini  12  Female   65000   25

In [157]:
df1.loc[[102,103],'Salary']=[80000,90000]

In [158]:
df1

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male   95000   37
102             Kartik   2    Male   80000   41
103          Aishwarya   3  Female   90000   41
104              Anand   4    Male   65000   46
105            Shalini   5    Male   90000   44
106             Pratik   6    Male   80000   30
107           Monalika   7  Female   70000   32
108             Ayesha   8  Female   60000   42
109              Anant   9    Male  100000   39
110          Shamiksha  10  Female   45000   38
111           Prashant  11    Male   55000   39
112             Mohini  12  Female   65000   25

## Querying based on Condition

In [160]:
df1

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male   95000   37
102             Kartik   2    Male   80000   41
103          Aishwarya   3  Female   90000   41
104              Anand   4    Male   65000   46
105            Shalini   5    Male   90000   44
106             Pratik   6    Male   80000   30
107           Monalika   7  Female   70000   32
108             Ayesha   8  Female   60000   42
109              Anant   9    Male  100000   39
110          Shamiksha  10  Female   45000   38
111           Prashant  11    Male   55000   39
112             Mohini  12  Female   65000   25

In [162]:
df1.Age>40

Employee_ID
101    False
102     True
103     True
104     True
105     True
106    False
107    False
108     True
109    False
110    False
111    False
112    False
Name: Age, dtype: bool

In [167]:
(df1.Age > 40) & (df1.Salary < 80000)

Employee_ID
101    False
102    False
103    False
104     True
105    False
106    False
107    False
108     True
109    False
110    False
111    False
112    False
dtype: bool

In [168]:
df1[df1.Age>40]
#you’re doing boolean indexing — you give pandas a Series of True/False values (one for each row), and it returns only the rows where the value is True.


#Why can’t we just write inside Age > 40 directly?

#If you wrote just:

#df1[Age > 40]


#pandas wouldn’t know what Age is.

#Age is not a standalone Python variable — it’s a column inside df1.

#To tell pandas which column you’re talking about, you must access it first:

                  Name  ID  Gender  Salary  Age
Employee_ID
102             Kartik   2    Male   80000   41
103          Aishwarya   3  Female   90000   41
104              Anand   4    Male   65000   46
105            Shalini   5    Male   90000   44
108             Ayesha   8  Female   60000   42

In [169]:
df1[df1.Age>40][['Name','Age','Salary']]

                  Name  Age  Salary
Employee_ID
102             Kartik   41   80000
103          Aishwarya   41   90000
104              Anand   46   65000
105            Shalini   44   90000
108             Ayesha   42   60000

In [170]:
df1[df1['Salary']<70000]

                  Name  ID  Gender  Salary  Age
Employee_ID
104              Anand   4    Male   65000   46
108             Ayesha   8  Female   60000   42
110          Shamiksha  10  Female   45000   38
111           Prashant  11    Male   55000   39
112             Mohini  12  Female   65000   25

In [171]:
df1[df1.Gender=='Male']

                 Name  ID Gender  Salary  Age
Employee_ID
101           Utkarsh   1   Male   95000   37
102            Kartik   2   Male   80000   41
104             Anand   4   Male   65000   46
105           Shalini   5   Male   90000   44
106            Pratik   6   Male   80000   30
109             Anant   9   Male  100000   39
111          Prashant  11   Male   55000   39

In [172]:
df1[df1.Gender=='Male'][df1.Salary>80000]

/tmp/ipython-input-470749794.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df1[df1.Gender=='Male'][df1.Salary>80000]

                Name  ID Gender  Salary  Age
Employee_ID
101          Utkarsh   1   Male   95000   37
105          Shalini   5   Male   90000   44
109            Anant   9   Male  100000   39

In [174]:
df1[(df1.Gender=='Female') & (df1.Salary<100000)]

                  Name  ID  Gender  Salary  Age
Employee_ID
103          Aishwarya   3  Female   90000   41
107           Monalika   7  Female   70000   32
108             Ayesha   8  Female   60000   42
110          Shamiksha  10  Female   45000   38
112             Mohini  12  Female   65000   25

In [175]:
df1[(df1.Age<30) | (df1.Age<45)]

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male   95000   37
102             Kartik   2    Male   80000   41
103          Aishwarya   3  Female   90000   41
105            Shalini   5    Male   90000   44
106             Pratik   6    Male   80000   30
107           Monalika   7  Female   70000   32
108             Ayesha   8  Female   60000   42
109              Anant   9    Male  100000   39
110          Shamiksha  10  Female   45000   38
111           Prashant  11    Male   55000   39
112             Mohini  12  Female   65000   25

In [176]:
df1[df1.Gender=='Male'][df1.Salary>80000][df1.Salary<120000][['Name','Gender','Salary']]

/tmp/ipython-input-4205240928.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df1[df1.Gender=='Male'][df1.Salary>80000][df1.Salary<120000][['Name','Gender','Salary']]
/tmp/ipython-input-4205240928.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df1[df1.Gender=='Male'][df1.Salary>80000][df1.Salary<120000][['Name','Gender','Salary']]

                Name Gender  Salary
Employee_ID
101          Utkarsh   Male   95000
105          Shalini   Male   90000
109            Anant   Male  100000

In [177]:
df1.query('Salary>70000')

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male   95000   37
102             Kartik   2    Male   80000   41
103          Aishwarya   3  Female   90000   41
105            Shalini   5    Male   90000   44
106             Pratik   6    Male   80000   30
109              Anant   9    Male  100000   39

In [178]:
df1.query('Salary>70000')['Name']

Employee_ID
101      Utkarsh
102       Kartik
103    Aishwarya
105      Shalini
106       Pratik
109        Anant
Name: Name, dtype: object

In [182]:
df1.query('Gender=="Male"')

                 Name  ID Gender  Salary  Age
Employee_ID
101           Utkarsh   1   Male   95000   37
102            Kartik   2   Male   80000   41
104             Anand   4   Male   65000   46
105           Shalini   5   Male   90000   44
106            Pratik   6   Male   80000   30
109             Anant   9   Male  100000   39
111          Prashant  11   Male   55000   39

In [183]:
df1.query('Salary>70000 and Age>40')

                  Name  ID  Gender  Salary  Age
Employee_ID
102             Kartik   2    Male   80000   41
103          Aishwarya   3  Female   90000   41
105            Shalini   5    Male   90000   44

In [185]:
df1.query('Gender=="Male" and Salary>70000')[['Name','Gender','Salary']]

                Name Gender  Salary
Employee_ID
101          Utkarsh   Male   95000
102           Kartik   Male   80000
105          Shalini   Male   90000
106           Pratik   Male   80000
109            Anant   Male  100000

In [188]:
df1.Salary.mean()

np.float64(74583.33333333333)

In [190]:
df1.query('Salary>{}'.format(df1.Salary.mean()))

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male   95000   37
102             Kartik   2    Male   80000   41
103          Aishwarya   3  Female   90000   41
105            Shalini   5    Male   90000   44
106             Pratik   6    Male   80000   30
109              Anant   9    Male  100000   39

In [191]:
df1.query('Salary>'+str(df1.Salary.mean()))

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male   95000   37
102             Kartik   2    Male   80000   41
103          Aishwarya   3  Female   90000   41
105            Shalini   5    Male   90000   44
106             Pratik   6    Male   80000   30
109              Anant   9    Male  100000   39